# Generated by Django 4.1.4 on 2022-12-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('year_published', models.IntegerField()),
                ('publisher', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('number_of_players', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('difficulty', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
