# Generated by Django 4.1.4 on 2022-12-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_club_apps', '0006_loan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='status',
        ),
    ]
